[package]
name = "sandstorm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
getopts = "0.2.21"
thiserror = "1.0.29"
typed-builder = "0.9.1"
